[package]
name = "anilist-youranimes"
version.workspace = true
edition.workspace = true

[dependencies]
anilist-core.workspace = true
anilist-nextjs.workspace = true
anilist-source.workspace = true
chrono.workspace = true
chrono-tz = { workspace = true, optional = true }
futures = { workspace = true, optional = true }
futures-timer = { workspace = true, optional = true }
iana-time-zone = { workspace = true, optional = true }
reqwest = { workspace = true, optional = true }
serde = { workspace = true, features = ["derive"] }
serde_json.workspace = true
thiserror.workspace = true

[dev-dependencies]
tokio = { version = "1", features = ["macros", "rt-multi-thread"] }

[features]
default = []
http = ["dep:futures", "dep:futures-timer", "dep:reqwest"]
system-timezone = ["anilist-core/clock", "anilist-core/timezone", "dep:chrono-tz", "dep:iana-time-zone"]
