[package]
name = "anilist-youranimes"
version.workspace = true
edition.workspace = true

[dependencies]
anilist-core.workspace = true
anilist-nextjs.workspace = true
anilist-source.workspace = true
async-stream.workspace = true
chrono.workspace = true
chrono-tz.workspace = true
futures.workspace = true
futures-timer.workspace = true
iana-time-zone.workspace = true
reqwest.workspace = true
scraper.workspace = true
serde.workspace = true
serde_json.workspace = true

[dev-dependencies]
tokio = { version = "1", features = ["macros", "rt-multi-thread"] }
