[package]
name = "anilist-iced"
version.workspace = true
edition.workspace = true

[[bin]]
name = "anilist"
path = "src/main.rs"

[dependencies]
anilist-core = { workspace = true, features = ["clock"] }
anilist-source.workspace = true
anilist-youranimes = { workspace = true, features = ["http", "system-timezone"] }
chrono = { workspace = true, features = ["clock"] }
iced.workspace = true
open.workspace = true
reqwest.workspace = true

[build-dependencies]
winresource.workspace = true
