[package]
name = "anilist-iced"
version.workspace = true
edition.workspace = true

[[bin]]
name = "anilist"
path = "src/main.rs"

[dependencies]
anilist-core.workspace = true
anilist-source.workspace = true
anilist-youranimes.workspace = true
chrono.workspace = true
iced.workspace = true
open.workspace = true
reqwest.workspace = true
tokio.workspace = true
