[package]
name = "anilist-iced"
version.workspace = true
edition.workspace = true

[dependencies]
anilist-core = { path = "../anilist-core" }
anilist-source = { path = "../anilist-source" }
anilist-youranimes = { path = "../anilist-youranimes" }
reqwest = "0.13.4"
chrono = "0.4.45"
tokio = { version = "1.53.1", features = ["full"] }
iced = { version = "0.14.0", features = ["tokio", "image"] }
