[package]
name = "anilist-ffi"
version.workspace = true
edition.workspace = true

[lib]
crate-type = ["cdylib", "rlib", "staticlib"]
name = "anilist"

[dependencies]
anilist-core.workspace = true
anilist-source.workspace = true
anilist-youranimes = { workspace = true, optional = true }
chrono.workspace = true
reqwest = { workspace = true, optional = true }
serde_json.workspace = true
thiserror.workspace = true
uniffi.workspace = true

[features]
default = ["http", "system-timezone", "youranimes"]
http = ["anilist-youranimes?/http", "dep:reqwest", "uniffi/tokio"]
system-timezone = ["anilist-core/clock", "anilist-youranimes?/system-timezone"]
youranimes = ["dep:anilist-youranimes"]
